#!perl

# ABSTRACT: Open a browser window with the GitHub URL of the repository which you are currently inside of
# PODNAME: gh-open

use strict;
use warnings;
use say;

use Browser::Open qw( open_browser );
use Getopt::Long qw( GetOptions );
use Git::Helpers qw( https_remote_url );

my $branch;
my $echo;
GetOptions( branch => \$branch, echo => \$echo );

# https_remote_url( $remote_name, $use_current_branch )
my $url = https_remote_url( shift @ARGV, $branch );
if ($echo) {
    say $url;
}
else {
    open_browser($url);
}
exit;

__END__
=pod

=head1 SYNOPSIS

    # open repo for "origin" on GitHub using your default browser
    gh-open

    # open repo for "upstream" on GitHub using your default browser
    gh-open upstream

    # open repo to your current branch
    gh-open -b
    gh-open -b upstream

    # print (echo) URL to screen rather than opening it
    gh-open -e
    gh-open -e -b
    gh-open -e -b upstream

=cut
